"""Full-extractor (size-``d`` X/Z bridge) feasibility filter — condition C5.

The *full extractor* of the logical-Pauli extractor kit is one fixed apparatus
that measures any logical Pauli of a CSS code by re-aiming. It couples a
cycle-graph X-extractor and Z-extractor with a fixed ``[d, 1, d]`` **bridge**
(a repetition chain of length = the code distance ``d``). To preserve distance,
the bridge must attach to a simple path of ``d`` **non-pivot** vertices in each
graph: an ``alpha``-path of X-only data qubits in ``G_X`` and a ``beta``-path of
Z-only data qubits in ``G_Z``. That requirement is the extractor kit's
**condition C5**; when it fails, the full extractor cannot be built (the
single-basis extractor and surgery gadgets, which have no bridge, are
unaffected).

This module decides C5 **exactly** from ``(Hx, Hz, Lx, Lz, d)`` — group-agnostic,
public-numpy only. It reproduces the kit's graph bit-for-bit: data qubits on a
logical's support are the graph vertices; each opposite-type check rings its
sorted support (consecutive pairs, de-duplicated) into edges; the path search
runs on the induced subgraph of the *non-pivot* block (so an edge that a check's
ring routes through a pivot is correctly absent after pivot deletion).

Why this is a meaningful, structural gate (the group-theoretic picture
:func:`bridge_subgroup_order` documents): for the 1x2 G-orbit LP codes the
non-pivot block is a Cayley graph ``Cay(G, S)`` whose connected components are
cosets of ``H = <S>``; a simple path cannot leave a coset, so the longest path is
at most ``|H|`` and **C5 needs ``|<S>| >= d`` on both sides**. ``|<S>|`` is the
order of the (cyclic) subgroup generated by the difference set of a weight-3 ring
anchor — i.e. visible in the classical lift. The exact graph check here is the
authoritative test (the component the path actually lives on is computed
directly, not inferred from one anchor, which the canonical basis can route
through the *free* anchor rather than the full-rank one).
"""

from __future__ import annotations

import numpy as np


# ---------------------------------------------------------------------------
# cycle-graph machinery (bit-identical to the extractor kit's CycleExtractor)
# ---------------------------------------------------------------------------


def _support_cols(L: np.ndarray) -> list[int]:
    """Columns where any row of ``L`` is nonzero (a logical block's support)."""
    L = np.asarray(L, np.uint8) & 1
    if L.size == 0:
        return []
    return np.flatnonzero(L.any(axis=0)).tolist()


def _nonpivot_induced_adj(
    graph_check: np.ndarray,
    own_support: list[int],
    nonpivot_cols: list[int],
) -> dict[int, list[int]]:
    """Adjacency (over data-qubit labels) of the cycle graph induced on the
    NON-PIVOT vertices.

    Built like the kit: the graph lives on ``own_support`` (a logical's full
    support = pivots + non-pivots); each row of ``graph_check`` (the
    opposite-type checks) rings its support restricted to ``own_support`` in
    sorted order (consecutive pairs, de-duplicated). We then keep only the edges
    whose *both* endpoints are non-pivot — exactly the subgraph the kit's
    ``path_in_subset(adj, nonpivot_vertices, d)`` walks (it never steps onto a
    pivot), so an edge a ring routes through a pivot vanishes here, which is why
    deleting pivots can fragment the block.
    """
    M = np.asarray(graph_check, np.uint8) & 1
    own = set(own_support)
    npv = set(nonpivot_cols)
    adj: dict[int, set] = {q: set() for q in nonpivot_cols}
    for r in range(M.shape[0]):
        ring = [c for c in np.flatnonzero(M[r]).tolist() if c in own]  # sorted asc
        w = len(ring)
        if w < 2:
            continue
        for i in range(w):
            u, v = ring[i], ring[(i + 1) % w]      # consecutive pair on the ring
            if u in npv and v in npv and u != v:
                adj[u].add(v)
                adj[v].add(u)
    return {q: sorted(vs) for q, vs in adj.items()}


def _max_component(adj: dict[int, list[int]]) -> int:
    """Size of the largest connected component (union-find sweep)."""
    seen: set = set()
    best = 0
    for s in adj:
        if s in seen:
            continue
        stack, sz = [s], 0
        seen.add(s)
        while stack:
            u = stack.pop()
            sz += 1
            for w in adj[u]:
                if w not in seen:
                    seen.add(w)
                    stack.append(w)
        best = max(best, sz)
    return best


def _has_simple_path(adj: dict[int, list[int]], length: int) -> bool:
    """Does a simple path of ``length`` distinct vertices exist? DFS that
    short-circuits the instant a length-``length`` path is reached.

    Mirrors the kit's ``path_in_subset`` (deterministic sorted DFS) but returns a
    bool and stops at ``length`` — so cost is bounded by the search for one path,
    not an enumeration.
    """
    if length <= 0:
        return True
    if len(adj) < length:
        return False
    for start in sorted(adj):
        stack = [(start, 1, frozenset((start,)))]
        while stack:
            node, depth, seen = stack.pop()
            if depth == length:
                return True
            for nb in adj[node]:
                if nb not in seen:
                    stack.append((nb, depth + 1, seen | {nb}))
    return False


def _side_has_bridge_path(
    graph_check: np.ndarray,
    own_L: np.ndarray,
    other_L: np.ndarray,
    d: int,
) -> bool:
    """One side of C5: does a length-``d`` simple path of non-pivot vertices exist?

    ``own_L`` = logicals of this side (Lx for the X-side, Lz for the Z-side);
    ``other_L`` = the opposite side, used only to locate the pivots
    (overlap = supp(own) ∩ supp(other)); ``graph_check`` = the opposite-type
    checks that build this side's graph (Hz for the X-side, Hx for the Z-side).
    """
    own_sup = _support_cols(own_L)
    other_sup = set(_support_cols(other_L))
    nonpivot = [c for c in own_sup if c not in other_sup]   # own-only block
    if len(nonpivot) < d:
        return False
    adj = _nonpivot_induced_adj(graph_check, own_sup, nonpivot)
    if _max_component(adj) < d:        # cheap necessary pre-screen
        return False
    return _has_simple_path(adj, d)    # exact existence (short-circuits at d)


# ---------------------------------------------------------------------------
# the filter predicate
# ---------------------------------------------------------------------------


def full_extractor_size_d_xz_bridge(
    Hx: np.ndarray,
    Hz: np.ndarray,
    Lx: np.ndarray,
    Lz: np.ndarray,
    d: int,
) -> bool:
    """``True`` iff the fixed size-``d`` X/Z bridge can be placed (condition C5).

    Exactly: a length-``d`` simple path of non-pivot **X-only** vertices exists in
    the X-extractor graph (rings of ``Hz`` over ``supp(Lx)``) **and** a length-``d``
    simple path of non-pivot **Z-only** vertices exists in the Z-extractor graph
    (rings of ``Hx`` over ``supp(Lz)``). This is the precondition for the
    extractor kit's ``full_extractor``; codes that fail it have no one-fixed-
    apparatus universal extractor (their single-basis extractors still build).

    Args:
        Hx, Hz: CSS parity-check matrices over GF(2), shape ``(*, n)``.
        Lx, Lz: a **standard-form** paired logical basis (``Lx · Lzᵀ = I_k`` over
            the integers, single-overlap pivots) — e.g. from
            ``logical_basis.find_logical_basis``. The pivot/X-only/Z-only block
            partition is read off ``supp(Lx)`` / ``supp(Lz)``.
        d: the code distance = required bridge length.

    Returns:
        ``True`` iff both length-``d`` non-pivot paths exist.

    Raises:
        ValueError: ``d < 1``, or column-count mismatch among the matrices.
    """
    if d < 1:
        raise ValueError(f"full_extractor_size_d_xz_bridge needs d >= 1; got d={d}")
    Hx = np.asarray(Hx, np.uint8) & 1
    Hz = np.asarray(Hz, np.uint8) & 1
    Lx = np.asarray(Lx, np.uint8) & 1
    Lz = np.asarray(Lz, np.uint8) & 1
    n = Hx.shape[1]
    if not (Hz.shape[1] == n and Lx.shape[1] == n and Lz.shape[1] == n):
        raise ValueError(
            f"Hx/Hz/Lx/Lz must share the column count n={n}; got "
            f"{Hz.shape[1]}, {Lx.shape[1]}, {Lz.shape[1]}"
        )
    # X-side: graph from Hz over supp(Lx); non-pivot = X-only = supp(Lx)\supp(Lz).
    if not _side_has_bridge_path(Hz, Lx, Lz, d):
        return False
    # Z-side: graph from Hx over supp(Lz); non-pivot = Z-only = supp(Lz)\supp(Lx).
    if not _side_has_bridge_path(Hx, Lz, Lx, d):
        return False
    return True


# ---------------------------------------------------------------------------
# group-theoretic characterization (documentation / fast analysis helper)
# ---------------------------------------------------------------------------


def full_extractor_bridge_from_rings(A: list, B: list, gd, d: int) -> bool:
    """Pairing-stage convenience: build the canonical code + orbit logical basis
    from ring matrices ``A``, ``B`` over ``F2[G]`` and test
    :func:`full_extractor_size_d_xz_bridge`.

    The full extractor needs the standard-form (single-overlap-pivot) orbit basis;
    a side without a full-rank block-column has no such basis, so the full
    extractor cannot be built and this returns ``False`` (it does NOT raise — an
    unstructured pair is a legitimate reject, not a programming error).

    Args:
        A, B: 1xn / mxn ring matrices (lists of lists of group-element-index
            tuples) for the two sides.
        gd: ``core.group.GroupData``.
        d: code distance = required bridge length.

    Returns:
        ``True`` iff the size-``d`` X/Z bridge can be placed on the canonical
        orbit basis of this ``(A, B, gd)`` code.

    Raises:
        ValueError: ``d < 1`` (propagated from the core predicate).
    """
    from core.quantum_code import build_quantum_code
    from logical_basis.logical_basis import find_logical_basis

    if d < 1:
        raise ValueError(f"full_extractor_bridge_from_rings needs d >= 1; got d={d}")
    qc = build_quantum_code(A, B, gd)
    if not (qc["has_full_rank_a"] and qc["has_full_rank_b"]):
        return False
    shape_a = (len(A), len(A[0]))
    shape_b = (len(B), len(B[0]))
    try:
        lb = find_logical_basis(
            qc["Hx"], qc["Hz"], qc["A_bin_canonical"], qc["B_bin_canonical"],
            gd.n, shape_a, shape_b,
        )
    except (RuntimeError, ValueError):
        # No clean single-orbit standard-form basis -> full extractor not buildable.
        return False
    return full_extractor_size_d_xz_bridge(qc["Hx"], qc["Hz"], lb["Lx"], lb["Lz"], d)


def bridge_subgroup_order(anchor, gd) -> int:
    """Order of the subgroup generated by the difference set of a ring anchor.

    For the 1x2 G-orbit LP family, the non-pivot connection graph on one side is
    ``Cay(G, S)`` with ``S = { u·v⁻¹ : u, v ∈ anchor, u ≠ v }`` the difference
    set of a weight-3 ring entry; the coset size (= max component, = the longest
    possible bridge path) is ``|<S>|``. So ``|<S>| >= d`` is the group-theoretic
    necessary condition behind C5 on that side.

    This is a *characterization / fast pre-screen*, NOT the authoritative test:
    which anchor lands in the X-only vs Z-only block is canonical-basis dependent
    (it can be the *free* anchor, not the full-rank one), so the exact decision
    must use :func:`full_extractor_size_d_xz_bridge` on the realized basis. Use
    this helper for analysis/explanation and cheap lower-bounding only.

    Args:
        anchor: iterable of 0-based group-element indices (a ring entry's support).
        gd: ``core.group.GroupData``.

    Returns:
        ``|<S>|`` — order of the generated subgroup (1 if the difference set is
        empty, i.e. ``|anchor| < 2``).
    """
    mult, inv, e, n = gd.mult, gd.inv, gd.identity, gd.n
    anchor = [int(g) for g in anchor]
    S = set()
    for u in anchor:
        for v in anchor:
            if u != v:
                S.add(int(mult[inv[u]][v]))
    S.discard(e)
    if not S:
        return 1
    H = {e}
    frontier = [e]
    gens = set(S) | {int(inv[s]) for s in S}
    while frontier:
        x = frontier.pop()
        for s in gens:
            y = int(mult[x][s])
            if y not in H:
                H.add(y)
                frontier.append(y)
    return len(H)
